Modification needed to run the bootstrap in swapforth/j1b/verilator with new version of Python 3. Without that, an error occurs:
Traceback (most recent call last):
  File "/tmp/swapforth/j1b/verilator/shell.py", line 53, in <module>
    swapforth.main(TetheredJ1b)
  File "../../shell/swapforth.py", line 385, in main
    r.shell()
  File "../../shell/swapforth.py", line 339, in shell
    self.shellcmd(cmd)
  File "../../shell/swapforth.py", line 197, in shellcmd
    d = self.serialize()
  File "/tmp/rr/swapforth/j1b/verilator/shell.py", line 49, in serialize
    s = array.array('B', s).tostring().ljust(32768, chr(0xff))
AttributeError: 'array.array' object has no attribute 'tostring'